# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aebd250a4494adafe05e4a43bca9a0c650ceceb66a5359613126dde1f28c0072d61806d5d594424b42a6dfb51d5837ef5f739e3fec27d2854fa8e770ad48130b

test:
  secret_key_base: 0727901e748321ea453d9d51228ef06b68a2c7a85e49f3744eb8e36b646ff261583537c2d588cacbec09175dc3842b2e6033568227192eace414109273bf7db4

staging:
  secret_key_base: 2e5e29b5edbc9aea2e3b8543cbc43aeaefc6f8b1b22458a233f2fa76adc894f65e6afd86063ad489fafef94e9d27e2de1b472f7e595bd4d2014bc73b5ee05150
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
